### PR TITLE
Admin password

### PR DESCRIPTION
**Pull request by aridge03**
Set the password for admin as SwiftCheckIn (not case sensitive) and start admin testing.

### CODE REVIEW

**Comment by poojabhambri** [comment]
Password stuff works fine but the test is failing for me, not sure if its just my emulator though?

**Comment by aridge03** [comment]
> Password stuff works fine but the test is failing for me, not sure if its just my emulator though?

Sometimes if my emulator is too slow it doesn't pass either looking into it!

**Review by aaryansingh-dev — APPROVED** [review]
LGTM

**Review by Praticus87 — COMMENTED** [review]
The password does work, but even for me, the test does not.

**Comment by poojabhambri** [comment]
i think the reason the test is failing for me is because i dont have the allow notifications popup every time so it cant even find that ui element

**Pull request closed without merging**
