### PR TITLE
Max attendees

### PR DESCRIPTION
**Pull request by Praticus87**
Made sure that there is an optional limit for the number of attendees to attend. 
When a person signs up for the event, they get added to the list of attendees who will sign up and a number keeping track of who signed up gets incremented. 
When the event is full, the sign up button for that particular event will grey out and when clicked again, it will say that the event is full.

Aside from that, an important note is that the event structure has changed in the sense that I added a new attribute called currentAttendees. If someone who hasn't pulled this code does not have the attribute, then this will crash. Small, but significant change.

### CODE REVIEW

**Review by poojabhambri — APPROVED** [review]
lgtm

**Review by poojabhambri — CHANGES_REQUESTED** [review]
Just retested it and the app won't open at all anymore. I'm getting this FATAL EXCEPTION: java.lang.AssertionError

**Comment by aaryansingh-dev** [comment]
For the changes made to the event class, you are not adding this new attribute to the constructor, so it should not cause any other class to crash when creating an event. Am I right?

**Review by poojabhambri — APPROVED** [review]

**Review by aaryansingh-dev — CHANGES_REQUESTED** [review]
App crashes for me. Pull the code from the main, and maybe will fix the issue.

**Comment by Praticus87** [comment]
> For the changes made to the event class, you are not adding this new attribute to the constructor, so it should not cause any other class to crash when creating an event. Am I right?

Yes, I wanted to avoid adding more elements to the constructor because it's already confusing enough.

**Review by aridge03 — APPROVED** [review]
Worked on my end

**Review by aaryansingh-dev — APPROVED** [review]

**Pull request merged**
