### PR TITLE
Attendee announcement & event section

### PR DESCRIPTION
**Pull request by kunaal-gupta**
Attendee announcement & event section

### CODE REVIEW

**Review by Praticus87 — COMMENTED** [review]
Could you check some of your ids? They've been written as ImageView2 or ImageView3.
Also, could you explain why two TextViews have the same ids?
Another thing is that you chose not to wrap content and instead made separate measurements. Could you explain that decision please?

**Comment by kunaal-gupta** [comment]
Updated ids in the xml files

**Review by poojabhambri — DISMISSED** [review]
Why did you change the settings page? I think its better for the dimensions to be wrapping the content than to have specific numbers. Also where have you implemented the listview? 

Your ids need to be changed as well

**Comment by kunaal-gupta** [comment]
Changed the dimensions to wrapping. Which ids' are you talking about? And list view where?

**Comment by kunaal-gupta** [comment]
- Added list view
- Refactored ids
- Changed to wrapping of content

**Comment by poojabhambri** [comment]
Why are you working on organizer and setting files? Those aren't related to your task. 
Also the ids im talking about are the ones that are like "ImageView2" etc. Those should be properly named. Also you got rid of the back button in the profile activity. Can you add that back in please?

**Comment by kunaal-gupta** [comment]
Awaiting my branch to be merged, before I can start with other tasks

**Review by Praticus87 — COMMENTED** [review]
Overall, it is good, but why are you changing the event class constructor? If you want to test it, that's fine, but we merge those changes into main.

Same thing with AddEventActivity, the changes will get in the way of how we'll code in the future.

**Review by Praticus87 — COMMENTED** [review]
Another thing in activity_profile.xml is that the ids are still named "imageView#." Could you change these?

**Review by Praticus87 — APPROVED** [review]
LGTM

**Review by amanvirsd — APPROVED** [review]
looks good

**Pull request merged**
